language: scala

# (from: https://github.com/scoverage/sbt-coveralls)
script:
  # sbt test
  - sbt clean coverage test
  # working-test of `sbt assembly`
  - sbt assembly
  # working-test of `sbt dist`
  - sbt dist

after_success:
  - sbt coverageReport coveralls

# (from: http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete


# (from: http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
