language: scala

# (from: https://github.com/scoverage/sbt-coveralls)
script:
  # sbt test
  - sbt clean coverage test
  # Generate a fat jar file
  - sbt assembly
  # working-test of `sbt dist`
  - sbt dist

after_success:
  - sbt coverageReport coveralls

# (from: https://docs.travis-ci.com/user/deployment/releases/)
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $TRAVIS_BUILD_DIR/target/scala-2.11/trans-server-akka.jar
  skip_cleanup: true
  on:
    tags: true

# (from: http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete


# (from: http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
